### ISSUE TITLE
Doesnt work for me

### ISSUE THREAD

**Issue by mhstnsc** [michitux/dokuwiki-plugin-outliner#3]
Dokuwiki version 2009-02-14b

What i wrote in empty new page

--> Title
- dodo

<--

Result (more or less)

–> Title

dodo

←-

**Comment by michitux** [comment]
Which version are you using? Are you using the "master" version or the "devel" version? They are completely different, I probably won't fix the "master" version. The devel version is a much cleaner rewrite of the plugin, I just need to test and improve it further before I will replace the master version.

**Comment by mhstnsc** [comment]
I tried using both the stable version and also 

http://github.com/michitux/dokuwiki-plugin-outliner/zipball/devel

If you want to see the output check out here

http://wiki.2am.ro/doku.php?id=start

**Comment by mhstnsc** [comment]
under 

Knowledge Base

**Comment by mhstnsc** [comment]
if you want me to place some info messages ... i really want this to work because as you can see in the page i extensively used the old plugin :)...and now im sitting duck :)

**Comment by michitux** [comment]
I've copied the page source into my own local wiki and most of it works. There are some little problems (some closing and opening tags aren't recognized) but all in all it seems to work. I've now changed the priority of the plugin, now your page source works here. Which other plugins do you have installed?

**Comment by mhstnsc** [comment]
i now have 2515a5e and still doesnt work.
1. I noticed that pressing Info for plugin says 
This plugin returned no information, it may be invalid.
1. i placed some print messages in getInfo and connectTo functions and are not called.
2. I made syntax error on syntax.php from the plugin and php yelds error so the source file is parsed by php

I have no other ideas :)

**Comment by mhstnsc** [comment]
My plugins are:

acl  
addnewpage  
config  
discussion  
displaywikipage  
emphasis  
favoris  
feed  
heise  
include  
indexmenu  
info  
michitux-dokuwiki-plugin-outliner-2515a5e  
mp3play  
newpagetemplate  
note  
odt  
pagemove  
plugin  
revert  
sidebarng  
stars  
tag  
usermanager

**Comment by mhstnsc** [comment]
i disabled all non essential plugins except for outliner and still problem

**Comment by michitux** [comment]
Could you try renaming the folder michitux-dokuwiki-plugin-outliner-2515a5e to outliner?

**Comment by mhstnsc** [comment]
yup..it works

**Comment by mhstnsc** [comment]
thanks...now i can start posting features :D

**Comment by michitux** [comment]
Uploaded a zip file for the master branch (the original plugin + fix) and linked it in the wiki so normal install should work now.
